<a target="_blank" href="https://colab.research.google.com/github/ZHAW-ZAV/TSO-FS26-students/blob/main/01_python_basics/01_02_intro_numpy.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Introduction to NumPy


## Importing NumPy

In [1]:
import numpy as np

## Creating arrays

### Creating a 1D array

In [2]:
a = np.array([43, 56, 35, 3])
print(a)
print(f"The shape is {a.shape}")
print(f"The size is {a.size}")
print(f"The type is {type(a)}")

[43 56 35  3]
The shape is (4,)
The size is 4
The type is <class 'numpy.ndarray'>


### Creating a 2D array

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(f"The shape is {a.shape}")
print(f"The size is {a.size}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
The shape is (3, 3)
The size is 9


### Creating a filled array

In [4]:
# create a 3x3 array of zeros
a = np.zeros((3, 3))
print(a)

# create a 3x3 array of 5s
a = np.ones((3, 3)) * 5
print(a)

# create a 3x3 identity matrix
a = np.eye(3)
print(a)

# create a 3x3 array of random numbers between 0 and 1
a = np.random.random((3, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.15870145 0.24759014 0.47595604]
 [0.4215226  0.95115647 0.96833961]
 [0.71367921 0.81367273 0.94935766]]


## Accessing elements
Remember that indices in Python start at 0.

In [5]:
a = np.array([10, 20, 30, 40])

print(f"The first element is {a[0]}")
print(f"The last element is {a[-1]}")
print(f"The first two elements are {a[0:2]}")
print(f"The last two elements are {a[-2:]}")

The first element is 10
The last element is 40
The first two elements are [10 20]
The last two elements are [30 40]


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"The element in the second row and third column is {a[1, 2]}")
print(f"The first row is {a[0, :]}")
print(f"The second column is {a[:, 1]}")
print(f"The first two rows are {a[:2, :]}")

## Array operations

In [ ]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])
c = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# addition/subtraction
print(a - 10)
print(a + b)

# element-wise multiplication/division
print(a * 2)
print(a / 2)

# matrix multiplication
print(np.matmul(a, b))
print(np.matmul(c, b))

In [6]:
a = np.array([10, 20, 30, 40])

# aggregation functions
print(a.sum())
print(a.mean())
print(a.std())
print(a.min())
print(a.max())

100
25.0
11.180339887498949
10
40
